version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.1-bullseye
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_PASSWORD}", "-h", "postgres" ]
      interval: 2s
      timeout: 3s
      retries: 40
