version: '3.8'

services:
  keycloak:
    extends:
      file: docker-compose.keycloak.yml
      service: keycloak
    networks:
      - development
        # ipv4_address: 172.20.1.1

  nginx:
    extends:
      file: docker-compose.nginx.yml
      service: nginx
    networks:
      - development
        # ipv4_address: 172.20.1.2

  postgres:
    extends:
      file: docker-compose.postgres.yml
      service: postgres
    networks:
      - development
        # ipv4_address: 172.20.1.3

  minio:
    extends:
      file: docker-compose.minio.yml
      service: minio
    networks:
      - development
      # development:
      #   ipv4_address: 172.20.1.4
  
  mongo:
    extends:
      file: docker-compose.mongo.yml
      service: mongo
    networks:
      - development
      # development:
      #   ipv4_address: 172.20.1.5

  rabbitmq:
    extends:
      file: docker-compose.rabbitmq.yml
      service: rabbitmq
    networks:
      - development
        # ipv4_address: 172.20.1.6

  redis:
    extends:
      file: docker-compose.redis.yml
      service: redis
    networks:
      - development
        # ipv4_address: 172.20.1.7



networks:
  development:
    name: development
    driver: bridge
    external: true
    # ipam:
    #  config:
    #    - subnet: 172.20.0.0/16
