version: '3.8'

services:
  minio:
    image: 'quay.io/minio/minio'
    container_name: minio
    restart: always
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/minio:/data
    command: server --console-address ":9001" --address "0.0.0.0:9000" /data
