services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    container_name: keycloak
#    command: ["start-dev", "--import-realm"]
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      # KC_DB: postgres
      # KC_DB_USERNAME: keycloak
      # KC_DB_PASSWORD: password
      # KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: INFO
      KC_REALM_NAME: development
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # GF_URL: ${GF_HOSTNAME}:${GF_SERVER_HTTP_PORT}
      # GF_ADMIN_USERNAME: ${GF_ADMIN_USERNAME}
      # GF_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}
    ports:
      - 8070:8080
#    volumes:
#      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
#    logging: *logging