version: '3.8'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432
